spring:
  redis:
    database: 6
    # Redis服务器地址
    host: 10.161.9.92
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
  rabbitmq:
    host: 10.161.9.92
    port: 5672
    username: fiona
    password: fiona
    publisherConfirms: true
    virtual-host: /
